### ISSUE TITLE
Time Invested vs. Time Wasted

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Distraction-Shield#128]
It would be nice to make a contraposition between "time wasted" and "time invested"

Currently the names are time wasted and time spent:

![screen shot 2018-12-06 at 5 07 24 pm](https://user-images.githubusercontent.com/464519/49595934-78eda780-f979-11e8-8eba-f954041aa0c8.png)

Also, there should be a "total time wasted" and a "total time invested" info.

**Comment by ancasuliman** [comment]
I am sorry @mircealungu, i did not see the issue you posted until You tagged me. I do not quite understand what You mean by contrapositioning the information given by ”time wasted” and ”time invested”. Should we arrange them in adjacent columns?

Regarding the ”total time wasted” and ”total time invested” information, I will start working on it, thank You for the suggestion.

Also, I have one suggestion, I am not sure whether I will be able to apply it, but I can try. I was thinking to display a line graph, which can provide information to the user about his/her evolution of time wasted on distraction sites or/and time spent exercising. My opinion is that visual representation of the statistics we acquire has more impact on users. 

What do you think? :)

**Comment by mircealungu** [comment]
Adjacent columns could be one way. Whatever is easier for you :)

Important to sum up all the time spent learning and make it
clearly comparable with the time spent "playing" :)

Graph would definitely look cool! Maybe open a new issue for
that though, because I think it might turn out to be more work
than this issue, and I would still prioritize the textual display
above that :)

**Comment by dunnkers** [comment]
Closing in favor of #156. Future development and features are tracked there, under the [`Beyond revival`](https://github.com/zeeguu-ecosystem/Distraction-Shield/milestone/2) milestone.

➡ #139 also elaborates about time wasted metric. This is probably not so difficult to do, but is a non- essential feature. Will be added later.
