### ISSUE TITLE
Revival

### ISSUE THREAD

**Issue by dunnkers** [zeeguu-ecosystem/Distraction-Shield#136]
## Goals 🏁
(`21.05.2019`)

1. Code cleanup
Currently, the codebase is `4713 lines of code`. We can reduce this by using libraries where possible and refactoring existing code. Such that our codebase gets more organised, enabling us to better and quicker develop new features.

<details>
<summary>
Lines of code per file
</summary>

### css files
```shell
λ wc -l ./Distraction\ Shield/**/*.css 
      24 ./Distraction Shield/dataCollection/dataCollection.css
      13 ./Distraction Shield/introTour/introTour.css
      14 ./Distraction Shield/introTour/tooltipcopy.css
     121 ./Distraction Shield/optionsPage/options.css
      15 ./Distraction Shield/statisticsPage/statistics.css
      17 ./Distraction Shield/tooltipPage/tooltip.css
     204 total
```

### html files
```shell
λ wc -l ./Distraction\ Shield/**/*.html                             
      30 ./Distraction Shield/contentInjection/inject.html
      21 ./Distraction Shield/dataCollection/dataCollectionFrame.html
      23 ./Distraction Shield/dataCollection/dataCollectionInfo.html
      23 ./Distraction Shield/introTour/introTour.html
     118 ./Distraction Shield/introTour/optionscopy.html
      29 ./Distraction Shield/introTour/tooltipcopy.html
     116 ./Distraction Shield/optionsPage/options.html
      61 ./Distraction Shield/statisticsPage/statistics.html
      22 ./Distraction Shield/tooltipPage/tooltip.html
     443 total
```

### js files

```shell
λ wc -l ./Distraction\ Shield/**/*.js scripts/**/*.js test/**/*.js Brocfile.js .eslintrc.js
     149 ./Distraction Shield/background.js
     115 ./Distraction Shield/classes/BlockedSite.js
     140 ./Distraction Shield/classes/BlockedSiteList.js
     191 ./Distraction Shield/classes/UserSettings.js
     135 ./Distraction Shield/constants.js
      70 ./Distraction Shield/contentInjection/inject.js
      59 ./Distraction Shield/dataCollection/dataCollection.js
     127 ./Distraction Shield/init.js
     123 ./Distraction Shield/introTour/introTour.js
      15 ./Distraction Shield/modules/UUIDGenerator.js
      46 ./Distraction Shield/modules/blockedSiteBuilder.js
      53 ./Distraction Shield/modules/browserutil.js
      29 ./Distraction Shield/modules/dateutil.js
     104 ./Distraction Shield/modules/logger.js
     298 ./Distraction Shield/modules/statistics/Tracker.js
      22 ./Distraction Shield/modules/statistics/exerciseTime.js
      99 ./Distraction Shield/modules/statistics/interception.js
      15 ./Distraction Shield/modules/storage/StorageListener.js
     284 ./Distraction Shield/modules/storage/storage.js
      55 ./Distraction Shield/modules/storage/storageModifier.js
      27 ./Distraction Shield/modules/stringutil.js
     209 ./Distraction Shield/modules/urlFormatter.js
     110 ./Distraction Shield/optionsPage/classes/BlacklistTable.js
     147 ./Distraction Shield/optionsPage/classes/GreenToRedSlider.js
      23 ./Distraction Shield/optionsPage/classes/IntervalSlider.js
     130 ./Distraction Shield/optionsPage/classes/TurnOffSlider.js
      63 ./Distraction Shield/optionsPage/connectDataToHtml.js
      70 ./Distraction Shield/optionsPage/htmlFunctionality.js
     229 ./Distraction Shield/optionsPage/options.js
      42 ./Distraction Shield/statisticsPage/classes/BasicTable.js
      29 ./Distraction Shield/statisticsPage/classes/BlacklistStatsTable.js
      26 ./Distraction Shield/statisticsPage/classes/ExerciseTimeTable.js
      28 ./Distraction Shield/statisticsPage/classes/InterceptionCounterTable.js
      84 ./Distraction Shield/statisticsPage/statistics.js
     188 ./Distraction Shield/tooltipPage/tooltip.js
      19 scripts/deploy-gh-pages.js
      54 test/classes/UserSettings-test.js
      16 test/modules/blockedSiteBuilder-test.js
      53 test/modules/browserutil-test.js
      25 test/modules/dateutil-test.js
      82 test/modules/storage/storage-test.js
      11 test/modules/stringutil-test.js
      80 test/modules/urlFormatter-test.js
     168 Brocfile.js
      24 .eslintrc.js
    4066 total
```
</details>

2. Make extension delightful to use
Make use of modern UI libraries and JS frameworks to implement progressive features - making the extension a delight to use.
3. Fix essential bugs
There exist some issues (#129, #131, #125, #128) that should be checked and dealt with, making sure extension works as advertised.
4. Publish to Chrome Webstore

_Note that, the codebase is first revised before the bugs are fixed. Some bugs might get resolved by revising the codebase._

## Analysis 📊
(`24.05.2019`)

**→ Let's get real**

We take a step back and analyse what value currently the extension brings to the user:

- We can add sites to block and enable/disable/remove them.
- We can turn off the extension temporarily.
- We can set 'time between intercepts'? This terminology is very confusing to users, what does this even mean?

_We should not hold on to everything in the app:_
- Lazy/pro mode overcomplicates things.
- Time sliders are not user-friendly.
- Intro-tour is buggy and long making users want to skip it. A good app should work self-explanatory.
- Statistics are inaccurate; time wasted tends to get extremely high without even having the website open.
- Zeeguu language learning website is down.

We are dealing with a couple competitors: (`28.05.2019`)
- wastenotime ([http://www.bumblebeesystems.com/wastenotime/](http://www.bumblebeesystems.com/wastenotime/))
  Fully functional, has block/allow list and time statistics. Ugly UI though and no changeable interception page.
- StayFocusd ([https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji](https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji))
- Block Site ([https://chrome.google.com/webstore/detail/block-site-website-blocke/eiimnmioipafcokbfikbljfdeojpcgbh](https://chrome.google.com/webstore/detail/block-site-website-blocke/eiimnmioipafcokbfikbljfdeojpcgbh))
- more... ([https://freedom.to/blog/8-website-blockers-for-studying-productivity-focus/](https://freedom.to/blog/8-website-blockers-for-studying-productivity-focus/))

## Implementation 💉

1. Code cleanup
(`24.05.2019`)
As a first attempt, we will try and transfer or even rewrite large portions of the code into a **react** app. We will use `create-react-app` as a starting point for this.

<img width="206" alt="Screenshot 2019-05-28 at 15 50 48" src="https://user-images.githubusercontent.com/744430/58483380-7c136480-8160-11e9-8cf9-d4161091fcee.png">

_Extension working using new setup. Functionality will be transferred over to the new setup._ (`28.05.2019`)

## Improvements summary
(`03.06.2019`)
- We no longer need an internet connection to block a url ( #129 )
- We can block multiple urls at the same time. e.g. typing `facebook.com, twitter.com` in the input blocks both.
- We have a smarter UI for better UX.
- We support both chrome sync storage and localStorage. Using chrome sync storage by default and falling back on localStorage.
🍻

**Comment by mircealungu** [comment]
nice analysis @dunnkers  :)

**Comment by mircealungu** [comment]
the zeeguu website is not down, it's just that it has moved to: 

    https://www.zeeguu.org/whatnext

m.

**Comment by dunnkers** [comment]
**Comments on the analysis during call:**

- Zeeguu website is not down, but the domain changed. Static url in application should be changed. ([https://www.zeeguu.org/whatnext](https://www.zeeguu.org/whatnext))
- Porting would be great, but can be a tedious process. In two weeks we decide on a go/no on the revival.
- If the revival fails, we are going to focus on the current codebase's issues & improvements.

✌🏻

**Comment by mircealungu** [comment]
static url should be changed to something but I doubt that /whatnext
that is the homepage for the web app.

**Comment by dunnkers** [comment]
New functionality in options page:

![Screenshot 2019-06-25 at 15 08 26](https://user-images.githubusercontent.com/744430/60100957-229c5680-975b-11e9-8f15-e1f81e1a4292.png)

Time left and 'continue' button:
![Screenshot 2019-06-25 at 15 09 25](https://user-images.githubusercontent.com/744430/60100987-31830900-975b-11e9-85ca-a76f300fc16d.png)

**Comment by dunnkers** [comment]
### Since `25-06-2019`

- Allow adding a custom interception learning page 💠 #145

**Comment by dunnkers** [comment]
Timeout selection tool

![Screenshot_2019-07-09_15-43-15](https://user-images.githubusercontent.com/744430/60892999-5fd70d00-a260-11e9-9413-a0faef409885.png)

Entire table

![Screenshot_2019-07-09_15-43-15](https://user-images.githubusercontent.com/744430/60893039-73827380-a260-11e9-8481-53e56b7a364e.png)

**Comment by dunnkers** [comment]
# 😍 ✌🏼
