### ISSUE TITLE
Twitter domain regex not matched - #129 regression

### ISSUE THREAD

**Issue by dunnkers** [zeeguu-ecosystem/Distraction-Shield#151]
#129 

## Edit `09-07-2019`
Reason is actually because indeed Twitter is a progressive app, and navigating on the page does not trigger a network request. Instead, all traffic is directed over its api at api.twitter.com. Same applies to facebook, where blocking the domain only leads to blocking the first request.

### 💡 Cause
Twitter block regex was not matched, cause twitter occludes its subdomain `www`.

Current:
`*://*.twitter.com/*`

Should be:
`*://twitter.com/*`

Then it works. We should check whether `www` was appended at all, or find a regex that accepts both.

**Comment by dunnkers** [comment]
@mircealungu I found out the reason of the twitter bug, it is because twitter remove its `www` subdomain, and the extension made an assumption of every url having a subdomain attached. It will be fixed!

**Comment by dunnkers** [comment]
Edit: re-adding the existing regex also seems to fix the problem, investigating further...

**Comment by mircealungu** [comment]
is this fixed? in the latest version on the revival branch, i still see this regex: *://*.twitter.com/* which seems to imply that there is a . expected before twitter.

**Comment by dunnkers** [comment]
Not fixed yet but I think I determined the problem at least.

Mircea Filip Lungu <notifications@github.com> schrieb am Fr., 5. Juli 2019,
12:10:

**Comment by dunnkers** [comment]
Closed by be88d1ebc5825bae56d9b2e2149043359fbe8700!

Now correctly blocks on the latest `revival` branch.
