### ISSUE TITLE
progress bar stands out too much

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Distraction-Shield#158]
is too colored in an UI where everything is quiet and thus, attracts too much the attention. either remove it, or make it to be gray. although removing would be just as ok. we don't want to distract the attention of the student with a moving thing, when their attention should be o the exercises.

<img width="832" alt="Screen Shot 2019-07-11 at 5 23 46 PM" src="https://user-images.githubusercontent.com/464519/61063792-d7dc3900-a400-11e9-9c43-5cf9e610574a.png">

**Comment by mircealungu** [comment]
probably the continue button centered, and the grayed timer inside it would be suffficient

**Comment by dunnkers** [comment]
Progressbar now is a very thin line at the bottom of the page:

![1](https://user-images.githubusercontent.com/744430/69971487-417bf180-1520-11ea-8f83-48c9f504b7d5.png)

It opens a menu with the button and text like before:
![2](https://user-images.githubusercontent.com/744430/69971314-fc57bf80-151f-11ea-9cf7-58a4d0fcad07.png)

The `<iframe>` has been re-adjusted to be completely full-screen. The menu is an overlay on top of the iframe, using fixed-position elements.
![3](https://user-images.githubusercontent.com/744430/69971323-fe218300-151f-11ea-9af3-1c01b7bca747.png)

Cheers 🎉
