### ISSUE TITLE
no exercise by default but the dropdown still says zeeguu

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Distraction-Shield#160]
after i uninstall the extension, when i install it from scratch i get this
sequence of behavior: 

(also, it seems that exercise duration is by default 00:00 which results in some infinite kind of loop where i try to press: go to twitter, and i'm still returned to the same page. 

can you replicate this @dunnkers ?)

<img width="784" alt="Screen Shot 2019-07-12 at 8 18 36 PM" src="https://user-images.githubusercontent.com/464519/61149926-84dab280-a4e2-11e9-9d42-7052098cf324.png">

<img width="789" alt="Screen Shot 2019-07-12 at 8 18 51 PM" src="https://user-images.githubusercontent.com/464519/61149925-84dab280-a4e2-11e9-9093-6e3a94354104.png">

<img width="789" alt="Screen Shot 2019-07-12 at 8 18 55 PM" src="https://user-images.githubusercontent.com/464519/61149924-84421c00-a4e2-11e9-9166-d90a36c0847d.png">

<img width="783" alt="Screen Shot 2019-07-12 at 8 18 59 PM" src="https://user-images.githubusercontent.com/464519/61149923-84421c00-a4e2-11e9-846c-5cab5996bb1a.png">

**Comment by dunnkers** [comment]
Replicated. Good bug find. Fixed in da46610f672759ad282c93685b0cf94f134354ee.
