### ISSUE TITLE
time passes when the browser does not have focus

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Distraction-Shield#161]
@dunnkers 

it seems that the counter still continues even when the browser loses focus. 
could it be related to this discussion here: https://stackoverflow.com/a/9502074/1200070? 

if you don't use it, probably the blur event would be the solution ?

**Comment by dunnkers** [comment]
Good find too. I only checked whether of the current window, the specified tab was selected.

Fixed in ec7b3835bf5c3b567b0731da82483d3eae709f3b. Using [`document.hasFocus()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus) now. 💎
