### ISSUE TITLE
Unlock development branch 🥦

### ISSUE THREAD

**Issue by dunnkers** [zeeguu-ecosystem/Distraction-Shield#164]
Hi M, 

Could you unlock the development branch for me, such that I can commit directly to `development` instead of having to PR to dev and then again to master?

Thx!

**Comment by mircealungu** [comment]
good idea! done.

**Comment by dunnkers** [comment]
👍🏻 thanks

Mircea Filip Lungu <notifications@github.com> schrieb am Sa., 13. Juli
2019, 22:30:
